name: pgvibe-kysely-tests

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvibe-kysely-postgres
    environment:
      POSTGRES_DB: kysely_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tests/integration/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kysely_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: pgvibe-kysely-network